name: 'run'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  watch:
    types: started
  schedule:
    - cron: '30 9,19 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: 'setup python'
       uses: actions/setup-python@master
       with: 
         python-version: 3.7
       
     - name: main
       env:
         SCKEY: ${{ secrets.SCKEY }}
         cookie_52pj: ${{ secrets.cookie_52pj }}
         cookie_smzdm: ${{ secrets.cookie_smzdm }}
         netease_username: ${{ secrets.netease_username }}
         netease_password: ${{ secrets.netease_password }}
         username_houqijun: ${{ secrets.username_houqijun }}
         password_houqijun: ${{ secrets.password_houqijun }}
         username_moke08: ${{ secrets.username_moke08 }}
         password_moke08: ${{ secrets.password_moke08 }}
         cookie_52programer: ${{ secrets.cookie_52programer }}
       run: |
         sudo cp -p ./chromedriver /usr/bin/
         chmod -R 777 /usr/bin/chromedriver
         pip3 install -r requirements.txt
         python3 ./Cloud189Checkin/C189CheckinForSCF.py
         python3 ./Checkin52pj/Checkin52pjForSCF.py
         python3 ./smzdmCheckin/smzdmCheckinForSCF.py
         python3 ./NetEase_Music_daily/NetEase_Music_dailyForSCF.py
         python3 ./CheckinHouqijun/CheckinHouQiJunForSCF.py
         python3 ./CheckinMoke08/CheckinMoke08ForSCF.py
         python3 ./Checkin52Programer/Checkin52ProgramerForSCF.py
